name: Lint and run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: shellcheck
        run: shellcheck *.sh test/*.bats test/*.bash

  bats:
    needs: shellcheck
    name: bats test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, macos-latest, macos-15-intel]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@3.0.1

      - name: Run bats test
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        run: bats test
