name: Release please

on:
  workflow_run:
    workflows: ["Lint and run tests"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Build and upload Release Asset
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          VERSION=${{ steps.release.outputs.tag_name }}
          TARBALL_NAME="nv-${VERSION}.tar.gz"

          tar -czf $TARBALL_NAME -C . nv.sh

          gh release upload "v$VERSION" $TARBALL_NAME \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
